name: 后台管理
identification: notadd/administration
description: 'Notadd 后台管理模块'
author:
    - twilroad
    - 269044570@qq.com
version: 2.0.0
csrf:
    - 'admin*'
    - 'api*'
    - 'editor*'
dashboards:
    -
        identification: systeminfo
        title: 系统信息
        template: Notadd\Administration\SystemInformation@handler
    -
        identification: development
        title: 开发团队
        template:
            -
                tag: p
                content:
                    -
                        tag: strong
                        content:
                            - 开发团队：
                    -
                        attrs:
                            href: https://github.com/twilroad
                            target: _blank
                        tag: a
                        content:
                            - 寻风
                    - ，
                    -
                        attrs:
                            href: https://www.zuohuadong.cn
                            target: _blank
                        tag: a
                        content:
                            - 依剑听雨
                    - ，
                    -
                        attrs:
                            href: https://github.com/medz
                            target: _blank
                        tag: a
                        content:
                            - Seven Du
                    - ，
                    -
                        attrs:
                            href: https://github.com/QiyueShiyi
                            target: _blank
                        tag: a
                        content:
                            - Luff
                    - ，
                    -
                        attrs:
                            href: https://weibo.com/u/2181906365
                            target: _blank
                        tag: a
                        content:
                            - 小莫
                    - ，
                    -
                        attrs:
                            href: https://weibo.com/u/3189357545
                            target: _blank
                        tag: a
                        content:
                            - 睡不醒的酸柠檬
                    - ，
                    -
                        attrs:
                            href: http://weibo.com/u/3854583077
                            target: _blank
                        tag: a
                        content:
                            - 浅殤
                    - ，
                    -
                        attrs:
                            href: https://weibo.cn/u/3258236872
                            target: _blank
                        tag: a
                        content:
                            - 马镝清同学
                    - ，
                    -
                        attrs:
                            href: http://weibo.com/u/5592753739
                            target: _blank
                        tag: a
                        content:
                            - 未央花事结
                    - 。
            -
                tag: p
                content:
                    -
                        tag: strong
                        content:
                            - 开发团队：
                    -
                        attrs:
                            href: https://github.com/LitoMore
                            target: _blank
                        tag: a
                        content:
                            - LitoMore
                    - ，
                    -
                        attrs:
                            href: https://github.com/ganlanshu0211
                            target: _blank
                        tag: a
                        content:
                            - 半缕阳光
                    - ，
                    -
                        attrs:
                            href: https://github.com/ToxinSting
                            target: _blank
                        tag: a
                        content:
                            - Rayle
                    - ，
                    -
                        attrs:
                            href: https://github.com/cloudsher
                            target: _blank
                        tag: a
                        content:
                            - cloudSher
                    - ，
                    -
                        attrs:
                            href: http://www.lovetd.cn
                            target: _blank
                        tag: a
                        content:
                            - 怒杀一只鸡
                    - 。
events:
    subscribes:
        - Notadd\Administration\Subscribers\RouteRegister
menus:
    global:
        icon: settings
        permission:
        path: '/'
        text: 全局
pages:
    configurations:
        initialization:
            name: 参数配置
            tabs: true
            target: global
        tabs:
            configuration:
                default: true
                show: true
                submit: api/setting/set
                title: 全局设置
                fields:
                    name:
                        default: ''
                        description: ''
                        label: 网站名称
                        key: site.name
                        placeholder: 请输入网站名称
                        required: true
                        type: input
                        validates:
                            -
                                message: 请输入网站名称
                                required: true
                                trigger: change
                                type: string
                    enabled:
                        default: false
                        description: '关闭后网站将不能访问'
                        format: boolean
                        label: 站点开启
                        key: site.enabled
                        required: false
                        type: switch
                    domain:
                        default: ''
                        description: '不带 http:// 或 https://'
                        label: 网站域名
                        key: site.domain
                        required: false
                        type: input
                    multidomain:
                        default: false
                        description: '由于前后端分离机制，官方不对多域名做特殊支持，可能导致其他未知问题'
                        format: boolean
                        label: 开启多域名
                        key: site.multidomain
                        required: false
                        type: switch
                    beian:
                        default: ''
                        label: 备案信息
                        key: site.beian
                        required: false
                        type: input
                    company:
                        default: ''
                        label: 公司名称
                        key: site.company
                        required: false
                        type: input
                    copyright:
                        default: ''
                        label: 版权信息
                        key: site.copyright
                        required: false
                        type: input
                    statistics:
                        default: ''
                        label: 统计代码
                        key: site.statistics
                        required: false
                        type: textarea
publishes:
    assets/admin: resources/mixes/administration/dist/assets/admin